/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookwise.UI;

/**
 *
 * @author wsr
 */
public class AddBookModel extends javax.swing.JFrame {

    /**
     * Creates new form AddBookModel
     */
    public AddBookModel() {
        initComponents();
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBoxTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBoxISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBoxAuthor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBoxCategory = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numericUpDownNoOfBooks = new javax.swing.JSpinner();
        buttonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Book");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(248, 248, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Title");

        txtBoxTitle.setPreferredSize(new java.awt.Dimension(391, 29));
        txtBoxTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxTitleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("ISBN  No");

        txtBoxISBN.setPreferredSize(new java.awt.Dimension(391, 29));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Author");

        txtBoxAuthor.setPreferredSize(new java.awt.Dimension(391, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Category");

        txtBoxCategory.setPreferredSize(new java.awt.Dimension(391, 29));
        txtBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxCategoryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Total  Number Of Books");

        numericUpDownNoOfBooks.setPreferredSize(new java.awt.Dimension(391, 29));

        buttonSave.setBackground(new java.awt.Color(37, 56, 140));
        buttonSave.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setText("Add  Book");
        buttonSave.setFocusPainted(false);
        buttonSave.setMargin(new java.awt.Insets(3, 3, 3, 3));
        buttonSave.setPreferredSize(new java.awt.Dimension(391, 50));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numericUpDownNoOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtBoxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtBoxISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtBoxTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1))
                    .addContainerGap(47, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(txtBoxTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtBoxISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtBoxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(numericUpDownNoOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private bookwise.DataAccess.Book bookToEdit = null;

    public AddBookModel(bookwise.DataAccess.Book book) {
        this(); // Call default constructor to init components
        this.bookToEdit = book;
        if (book != null) {
            setTitle("Edit Book");
            buttonSave.setText("Update Book");
            txtBoxTitle.setText(book.getTitle());
            txtBoxISBN.setText(book.getIsbn()); // ISBN might be uneditable? Let's allow for now but maybe check usage.
            txtBoxAuthor.setText(book.getAuthor());
            txtBoxCategory.setText(book.getCategory());
            numericUpDownNoOfBooks.setValue(book.getAvailableBooks());
        }
    }

    private void txtBoxTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxTitleActionPerformed

    private void txtBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxCategoryActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        String title = txtBoxTitle.getText().trim();
        String isbn = txtBoxISBN.getText().trim();
        String author = txtBoxAuthor.getText().trim();
        String category = txtBoxCategory.getText().trim();
        int availableBooks = (int) numericUpDownNoOfBooks.getValue();

        if (title.isEmpty() || isbn.isEmpty() || author.isEmpty() || category.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (availableBooks < 0) {
             javax.swing.JOptionPane.showMessageDialog(this, "Number of books cannot be negative", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
             return;
        }

        bookwise.DataAccess.Book bookObj = new bookwise.DataAccess.Book();
        if (bookToEdit != null) {
            bookObj = bookToEdit; // Use the existing object to keep ID
        }

        bookObj.setTitle(title);
        bookObj.setIsbn(isbn);
        bookObj.setAuthor(author);
        bookObj.setCategory(category);
        bookObj.setAvailableBooks(availableBooks);

        if (bookToEdit == null) {
            // New entry
            if (bookObj.isExisting()) {
               javax.swing.JOptionPane.showMessageDialog(this, "A book with this ISBN already exists", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                if (bookObj.add()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Book added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    this.dispose(); // Close the window
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to add book", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // Update existing
            if (bookObj.update()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Book updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                 javax.swing.JOptionPane.showMessageDialog(this, "Failed to update book", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner numericUpDownNoOfBooks;
    private javax.swing.JTextField txtBoxAuthor;
    private javax.swing.JTextField txtBoxCategory;
    private javax.swing.JTextField txtBoxISBN;
    private javax.swing.JTextField txtBoxTitle;
    // End of variables declaration//GEN-END:variables
}
