/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookwise.UI;

import bookwise.DataAccess.User;

/**
 *
 * @author wsr
 */
public class AddUserModel extends javax.swing.JFrame {
    
    private User userToEdit;

    /**
     * Creates new form AddUserModel
     */
    public AddUserModel() {
        initComponents();
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo.png")));
        restrictRolesForStaff();
        checkRolePermissions();
    }

    public AddUserModel(User user) {
        initComponents();
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo.png")));
        this.userToEdit = user;
        restrictRolesForStaff();
        populateForm();
        checkRolePermissions();
    }

    private void restrictRolesForStaff() {
        if ("Staff".equalsIgnoreCase(HomeForm.userRole)) {
            comboBoxRole.removeAllItems();
            comboBoxRole.addItem("Student");
        }
    }

    private void populateForm() {
        if (userToEdit == null) return;
        
        setTitle("Edit User");
        buttonSave.setText("Update User");
        
        numericUpDownId.setValue(userToEdit.getId());
        textBoxFName.setText(userToEdit.getFirstName());
        textBoxLName.setText(userToEdit.getLastName());
        textBoxEmail.setText(userToEdit.getEmail());
        textBoxNic.setText(userToEdit.getNic());
        txtBoxPhoneNo.setText(userToEdit.getPhone());
        textBoxAddress.setText(userToEdit.getAddress());
        comboBoxRole.setSelectedItem(userToEdit.getRole());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        comboBoxRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        textBoxEmail = new javax.swing.JTextField();
        textBoxAddress = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        textBoxConfirmPassword = new javax.swing.JPasswordField();
        txtBoxPhoneNo = new javax.swing.JTextField();
        checkBoxShowPassword = new java.awt.Checkbox();
        textBoxNic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textBoxLName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textBoxPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textBoxFName = new javax.swing.JTextField();
        numericUpDownId = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add User");
        setResizable(false);

        jToolBar1.setRollover(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(529, 547));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Password");

        comboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff", "Student" }));
        comboBoxRole.setMaximumSize(new java.awt.Dimension(0, 0));
        comboBoxRole.setMinimumSize(new java.awt.Dimension(0, 0));
        comboBoxRole.setPreferredSize(new java.awt.Dimension(145, 29));
        comboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRoleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Email");

        textBoxEmail.setMargin(new java.awt.Insets(3, 3, 3, 3));
        textBoxEmail.setPreferredSize(new java.awt.Dimension(303, 29));

        textBoxAddress.setMargin(new java.awt.Insets(3, 3, 3, 3));
        textBoxAddress.setPreferredSize(new java.awt.Dimension(462, 29));

        buttonSave.setBackground(new java.awt.Color(37, 56, 140));
        buttonSave.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setText("Add User");
        buttonSave.setFocusPainted(false);
        buttonSave.setMargin(new java.awt.Insets(3, 3, 3, 3));
        buttonSave.setMaximumSize(new java.awt.Dimension(0, 0));
        buttonSave.setMinimumSize(new java.awt.Dimension(0, 0));
        buttonSave.setPreferredSize(new java.awt.Dimension(462, 50));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        textBoxConfirmPassword.setPreferredSize(new java.awt.Dimension(220, 29));

        txtBoxPhoneNo.setMargin(new java.awt.Insets(3, 3, 3, 3));
        txtBoxPhoneNo.setMaximumSize(new java.awt.Dimension(0, 0));
        txtBoxPhoneNo.setMinimumSize(new java.awt.Dimension(0, 0));
        txtBoxPhoneNo.setPreferredSize(new java.awt.Dimension(145, 29));

        checkBoxShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkBoxShowPassword.setLabel("Show Password");
        checkBoxShowPassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxShowPasswordItemStateChanged(evt);
            }
        });

        textBoxNic.setMargin(new java.awt.Insets(3, 3, 3, 3));
        textBoxNic.setMaximumSize(new java.awt.Dimension(0, 0));
        textBoxNic.setMinimumSize(new java.awt.Dimension(0, 0));
        textBoxNic.setPreferredSize(new java.awt.Dimension(145, 29));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Phone  No");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Role");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Confirm Password");

        textBoxLName.setMargin(new java.awt.Insets(3, 3, 3, 3));
        textBoxLName.setPreferredSize(new java.awt.Dimension(220, 29));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Address");

        textBoxPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textBoxPassword.setMargin(new java.awt.Insets(3, 3, 3, 3));
        textBoxPassword.setPreferredSize(new java.awt.Dimension(220, 29));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("ID  No");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("NIC ");

        textBoxFName.setMargin(new java.awt.Insets(3, 3, 3, 3));
        textBoxFName.setPreferredSize(new java.awt.Dimension(220, 29));

        numericUpDownId.setPreferredSize(new java.awt.Dimension(145, 29));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numericUpDownId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBoxNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel6)
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBoxPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(textBoxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(142, 142, 142)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textBoxFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBoxLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(140, 140, 140))
                            .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(185, 185, 185)
                                .addComponent(jLabel10)
                                .addGap(82, 82, 82))
                            .addComponent(textBoxAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkBoxShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textBoxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textBoxConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numericUpDownId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBoxPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBoxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(checkBoxShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // Validate input fields
        if (!validateInputs()) {
            return;
        }

        if (userToEdit != null) {
            // Update existing user
            userToEdit.setFirstName(textBoxFName.getText().trim());
            userToEdit.setLastName(textBoxLName.getText().trim());
            userToEdit.setEmail(textBoxEmail.getText().trim());
            userToEdit.setNic(textBoxNic.getText().trim());
            userToEdit.setPhone(txtBoxPhoneNo.getText().trim());
            userToEdit.setAddress(textBoxAddress.getText().trim());
            String selectedRole = (String) comboBoxRole.getSelectedItem();
            userToEdit.setRole(selectedRole);
            
            // Allow updating ID only if necessary/safe, generally ID shouldn't change but logic allows it if code permits
             userToEdit.setId((Integer) numericUpDownId.getValue());

            String newPassword = new String(textBoxPassword.getPassword()).trim();
            if (!newPassword.isEmpty()) {
                userToEdit.setPassword(newPassword);
            } else {
                userToEdit.setPassword(null); // Signal not to change password
            }

            if (userToEdit.update()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "User updated successfully!", 
                    "Success", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to update user. Please try again.", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Create a User object and populate it with form data
            User user = new User();
            user.setFirstName(textBoxFName.getText().trim());
            user.setLastName(textBoxLName.getText().trim());
            user.setEmail(textBoxEmail.getText().trim());
            user.setNic(textBoxNic.getText().trim());
            user.setPhone(txtBoxPhoneNo.getText().trim());
            user.setAddress(textBoxAddress.getText().trim());
            String selectedRole = (String) comboBoxRole.getSelectedItem();
            user.setRole(selectedRole);
            
            // Only set ID and password for Admin role
            if ("Admin".equals(selectedRole)) {
                user.setId((Integer) numericUpDownId.getValue());
                user.setPassword(new String(textBoxPassword.getPassword()).trim());
            } else {
                user.setPassword(null);  // Staff and Students are beneficiaries, not system users
            }

            // Check for duplicate email or NIC
            if (user.isDuplicateEmailOrNic()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "User already exists with this Email or NIC.", 
                    "Duplicate User", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // For Admin role, also check for duplicate ID
            if ("Admin".equals(selectedRole) && user.isRegistered()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "User already exists with this ID.", 
                    "Duplicate User", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Register the user
            if (user.register()) {
                // Send Welcome Email
                String fullName = user.getFirstName() + " " + user.getLastName();
                new bookwise.Mails.UserRegisterMail(fullName).send(user.getEmail());

                javax.swing.JOptionPane.showMessageDialog(this, 
                    "User added successfully!", 
                    "Success", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Failed to add user. Please try again.", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void comboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRoleActionPerformed
        checkRolePermissions();
    }//GEN-LAST:event_comboBoxRoleActionPerformed

    private void checkBoxShowPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxShowPasswordItemStateChanged
        // TODO add your handling code here:
        if (checkBoxShowPassword.getState()) {
            textBoxPassword.setEchoChar((char) 0);
            textBoxConfirmPassword.setEchoChar((char) 0);
        } else {
            textBoxPassword.setEchoChar('\u2022');
            textBoxConfirmPassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_checkBoxShowPasswordItemStateChanged

    private boolean validateInputs() {
        // Check first name
        if (textBoxFName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "First Name is required.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            textBoxFName.requestFocus();
            return false;
        }

        // Check last name
        if (textBoxLName.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Last Name is required.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            textBoxLName.requestFocus();
            return false;
        }

        // Check email
        if (textBoxEmail.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Email is required.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            textBoxEmail.requestFocus();
            return false;
        }

        // Validate email format
        if (!isValidEmail(textBoxEmail.getText().trim())) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please enter a valid email address.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            textBoxEmail.requestFocus();
            return false;
        }

        // Check NIC
        if (textBoxNic.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "NIC is required.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            textBoxNic.requestFocus();
            return false;
        }

        // Check phone number
        if (txtBoxPhoneNo.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Phone Number is required.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            txtBoxPhoneNo.requestFocus();
            return false;
        }

        // Check address
        if (textBoxAddress.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Address is required.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            textBoxAddress.requestFocus();
            return false;
        }

        // Check role
        if (comboBoxRole.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please select a valid role.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            comboBoxRole.requestFocus();
            return false;
        }

        // Password is required only for Admin role
        String selectedRole = (String) comboBoxRole.getSelectedItem();
        if ("Admin".equals(selectedRole)) {
            String password = new String(textBoxPassword.getPassword()).trim();
            // If editing, allow empty password (means no change)
            if (password.isEmpty() && userToEdit == null) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Password is required for Admin role.", 
                    "Validation Error", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                textBoxPassword.requestFocus();
                return false;
            }

            if (password.length() < 6) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Password must be at least 6 characters long.", 
                    "Validation Error", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                textBoxPassword.requestFocus();
                return false;
            }

            String confirmPassword = new String(textBoxConfirmPassword.getPassword()).trim();
            if (!password.equals(confirmPassword)) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Passwords do not match.", 
                    "Validation Error", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                textBoxConfirmPassword.requestFocus();
                return false;
            }
        }

        return true;
    }

    private boolean isValidEmail(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        return email.matches(emailRegex);
    }

    private void clearForm() {
        numericUpDownId.setValue(0);
        textBoxFName.setText("");
        textBoxLName.setText("");
        textBoxEmail.setText("");
        textBoxNic.setText("");
        txtBoxPhoneNo.setText("");
        textBoxAddress.setText("");
        textBoxPassword.setText("");
        textBoxConfirmPassword.setText("");
        comboBoxRole.setSelectedIndex(0);
    }

    private void checkRolePermissions() {
        String role = (String) comboBoxRole.getSelectedItem();
        if ("Student".equalsIgnoreCase(role)) {
             jLabel9.setVisible(false);
             jLabel10.setVisible(false);
             textBoxPassword.setVisible(false);
             textBoxConfirmPassword.setVisible(false);
             checkBoxShowPassword.setVisible(false);
        } else {
             jLabel9.setVisible(true);
             jLabel10.setVisible(true);
             textBoxPassword.setVisible(true);
             textBoxConfirmPassword.setVisible(true);
             checkBoxShowPassword.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUserModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave;
    private java.awt.Checkbox checkBoxShowPassword;
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSpinner numericUpDownId;
    private javax.swing.JTextField textBoxAddress;
    private javax.swing.JPasswordField textBoxConfirmPassword;
    private javax.swing.JTextField textBoxEmail;
    private javax.swing.JTextField textBoxFName;
    private javax.swing.JTextField textBoxLName;
    private javax.swing.JTextField textBoxNic;
    private javax.swing.JPasswordField textBoxPassword;
    private javax.swing.JTextField txtBoxPhoneNo;
    // End of variables declaration//GEN-END:variables
}
