/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookwise.UI.Panels;

import bookwise.UI.FilterHistoryModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wsr
 */
public class HistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryControlPanel
     */
    public HistoryPanel() {
        initComponents();
        refreshData();
        configureTableColumns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataGridViewHistory = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(929, 541));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 41, 59));
        jLabel1.setText("Book  Transactions");
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(239, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 41, 59));
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 37));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\wsr\\Documents\\LMS java\\LibrarySystem\\images\\filter.png")); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(37, 37));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        // History transaction table
        dataGridViewHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBM No", "Title", "User id", "User name", "Borrow date", "Return date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataGridViewHistory.setPreferredSize(new java.awt.Dimension(889, 400));
        jScrollPane1.setViewportView(dataGridViewHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FilterHistoryModel addHistoryFrame = new FilterHistoryModel();
        addHistoryFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void refreshData() {
        DefaultTableModel model = (DefaultTableModel) dataGridViewHistory.getModel();
        model.setRowCount(0);  // Clear existing rows
    }

    private void configureTableColumns() {
        // Configure column headers and properties
        dataGridViewHistory.getColumnModel().getColumn(0).setHeaderValue("ISBM No");
        dataGridViewHistory.getColumnModel().getColumn(0).setPreferredWidth(120);
        
        dataGridViewHistory.getColumnModel().getColumn(1).setHeaderValue("Title");
        dataGridViewHistory.getColumnModel().getColumn(1).setPreferredWidth(200);
        
        dataGridViewHistory.getColumnModel().getColumn(2).setHeaderValue("User id");
        dataGridViewHistory.getColumnModel().getColumn(2).setPreferredWidth(80);
        
        dataGridViewHistory.getColumnModel().getColumn(3).setHeaderValue("User name");
        dataGridViewHistory.getColumnModel().getColumn(3).setPreferredWidth(150);
        
        dataGridViewHistory.getColumnModel().getColumn(4).setHeaderValue("Borrow date");
        dataGridViewHistory.getColumnModel().getColumn(4).setPreferredWidth(150);
        
        dataGridViewHistory.getColumnModel().getColumn(5).setHeaderValue("Return date");
        dataGridViewHistory.getColumnModel().getColumn(5).setPreferredWidth(150);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable dataGridViewHistory;
    // End of variables declaration//GEN-END:variables
}
