/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookwise.UI.Panels;

import bookwise.UI.AddUserModel;
import bookwise.DataAccess.User;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wsr
 */
public class UsersPanel extends javax.swing.JPanel {
    
    private String acceptedRoles = "Admin,Staff,Student";

    /**
     * Creates new form UsersPanel
     */
    public UsersPanel() {
        initComponents();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        
        // Table Styling
        jTable1.setShowVerticalLines(false);
        jTable1.setSelectionBackground(new java.awt.Color(244, 244, 244));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        jTable1.getTableHeader().setPreferredSize(new java.awt.Dimension(jTable1.getTableHeader().getPreferredSize().width, 40));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new java.awt.Color(248, 248, 255));
        jTable1.getTableHeader().setForeground(new java.awt.Color(30, 41, 59));
        
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane2.getViewport().setBackground(java.awt.Color.WHITE);

        initPopupMenu();
        loadUsersToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("All Users");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 116, 139));
        jLabel2.setText("Fillter  :");
        jLabel2.setPreferredSize(new java.awt.Dimension(46, 19));

        jComboBox1.setBackground(new java.awt.Color(248, 248, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(58, 53, 78));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All ", "Students", "Staff" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(101, 27));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(37, 56, 140));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add a New User");
        jButton1.setFocusPainted(false);
        jButton1.setMargin(new java.awt.Insets(3, 3, 3, 3));
        jButton1.setPreferredSize(new java.awt.Dimension(165, 41));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "NIC No", "Role", "Phone No", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(230, 230, 230));
        jTable1.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(jTable1);

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(102, 102, 102));
        txtSearch.setText("Search...");
        txtSearch.setPreferredSize(new java.awt.Dimension(250, 40));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Open AddUserModel window when button is clicked
        AddUserModel addUserFrame = new AddUserModel();
        addUserFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadUsersToTable();
            }
        });
        addUserFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Update accepted roles based on filter selection and refresh data
        int selectedIndex = jComboBox1.getSelectedIndex();
        if (selectedIndex == 0) {
            acceptedRoles = "Admin,Staff,Student";
        } else if (selectedIndex == 1) {
            acceptedRoles = "Student";
        } else if (selectedIndex == 2) {
            acceptedRoles = "Admin,Staff";
        }
        loadUsersToTable();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        if (txtSearch.getText().equals("Search...")) {
            txtSearch.setText("");
            txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // TODO add your handling code here:
        if (txtSearch.getText().isEmpty()) {
            txtSearch.setForeground(new java.awt.Color(102, 102, 102));
            txtSearch.setText("Search...");
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        loadUsersToTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    public void loadUsersToTable() {
        String searchText = txtSearch.getText();
        boolean isSearching = searchText != null && !searchText.trim().isEmpty() && !searchText.equals("Search...");

        javax.swing.SwingUtilities.invokeLater(() -> {
            setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            model.addRow(new Object[]{"Loading data...", "", "", "", "", "", "", ""});
        });

        new Thread(() -> {
            User[] users;
            if (isSearching) {
                users = User.search(searchText.trim(), acceptedRoles);
            } else {
                users = User.getAll(acceptedRoles);
            }

            javax.swing.SwingUtilities.invokeLater(() -> {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                for (User user : users) {
                    model.addRow(new Object[]{
                        user.getId(),
                        user.getFirstName(),
                        user.getLastName(),
                        user.getEmail(),
                        user.getNic(),
                        user.getRole(),
                        user.getPhone(),
                        user.getAddress()
                    });
                }
                setCursor(java.awt.Cursor.getDefaultCursor());
            });
        }).start();
    }

    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem menuItemEdit;
    private javax.swing.JMenuItem menuItemRemove;

    private void initPopupMenu() {
        popupMenu = new javax.swing.JPopupMenu();
        menuItemEdit = new javax.swing.JMenuItem("Edit");
        menuItemRemove = new javax.swing.JMenuItem("Remove");

        popupMenu.add(menuItemEdit);
        popupMenu.add(menuItemRemove);

        menuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUser();
            }
        });

        menuItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUser();
            }
        });

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showPopup(e);
                }
            }
            public void mousePressed(java.awt.event.MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showPopup(e);
                }
            }
            private void showPopup(java.awt.event.MouseEvent e) {
                int row = jTable1.rowAtPoint(e.getPoint());
                if (row >= 0 && row < jTable1.getRowCount()) {
                    jTable1.setRowSelectionInterval(row, row);
                    popupMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }

    private void editUser() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            User user = new User();
            try {
                user.setId(Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString()));
                user.setFirstName(jTable1.getValueAt(selectedRow, 1).toString());
                user.setLastName(jTable1.getValueAt(selectedRow, 2).toString());
                user.setEmail(jTable1.getValueAt(selectedRow, 3).toString());
                user.setNic(jTable1.getValueAt(selectedRow, 4).toString());
                user.setRole(jTable1.getValueAt(selectedRow, 5).toString());
                user.setPhone(jTable1.getValueAt(selectedRow, 6).toString());
                user.setAddress(jTable1.getValueAt(selectedRow, 7).toString());
                
                AddUserModel editFrame = new AddUserModel(user);
                editFrame.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent e) {
                        loadUsersToTable();
                    }
                });
                editFrame.setVisible(true);
            } catch (Exception ex) {
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error reading user data: " + ex.getMessage());
            }
        }
    }

    private void removeUser() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
             int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to remove this user?", 
                "Confirm Removal", 
                javax.swing.JOptionPane.YES_NO_OPTION);
             
             if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                 try {
                     int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
                     User user = new User();
                     user.setId(id);
                     if (user.remove()) {
                         javax.swing.JOptionPane.showMessageDialog(this, "User removed successfully.");
                         loadUsersToTable();
                     } else {
                         javax.swing.JOptionPane.showMessageDialog(this, "Failed to remove user.");
                     }
                 } catch (Exception ex) {
                     ex.printStackTrace();
                     javax.swing.JOptionPane.showMessageDialog(this, "Error removing user: " + ex.getMessage());
                 }
             }
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
